### ISSUE TITLE
Adding PackRat talent doesnt increase weight allowance

### ISSUE THREAD

**Issue by florianpiekert** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#199] opened 2022-03-10 08:47 UTC
Forbidden lands system module v8.2.1
Foundry Version 9 - Build 255

When adding the talent "Pack Rat" to a character and setting up the talent to provide the +2 on weight allowance (for rank 1), it does not increase the character's total weight allowance.

![01_Without_PackRat](https://user-images.githubusercontent.com/3978619/157624712-600034d1-b390-4862-a10d-ea171ee07c4a.jpg)
Without the talent in the char sheet.

![02_PackRat_added](https://user-images.githubusercontent.com/3978619/157624744-67751d9d-e528-4e03-abb9-2a1d12ec5b33.jpg)
![03_PackRat_details](https://user-images.githubusercontent.com/3978619/157624788-c16b2afa-869e-4d0b-adfe-a61e708e796e.jpg)
![04_PackRat_added_noChange](https://user-images.githubusercontent.com/3978619/157624828-3ab386d3-5645-4213-8644-ff087ecc34cb.jpg)

**Comment by narukaioh** [comment] 2022-03-10 17:55
Pretty weird, I just checked here and it's working

**Comment by florianpiekert** [comment] 2022-03-11 10:20
The error message I receive, when I drad the Rat Pack talent on player char sheet, is the following:

`Foundry VTT | Created Item with id [1KemginJIcNfKZB9] in parent Actor [HmJ1Fog2fqq8skfY] backend.mjs:306:18
Foundry VTT | Error thrown in hooked function 'bound includeActorLinks' for hook 'renderActorSheet' foundry.js:297:15
TypeError: entityData is undefined
[Detected 2 packages: journal-links, system:forbidden-lands]
    includeLinks https://foundryvtt.piekert.de:30000/modules/journal-links/scripts/journallink.js:117
    includeActorLinks https://foundryvtt.piekert.de:30000/modules/journal-links/scripts/journallink.js:109
    _call https://foundryvtt.piekert.de:30000/scripts/foundry.js:294
    call https://foundryvtt.piekert.de:30000/scripts/foundry.js:279
    _render https://foundryvtt.piekert.de:30000/scripts/foundry.js:3119
    _render https://foundryvtt.piekert.de:30000/scripts/foundry.js:3766
    render https://foundryvtt.piekert.de:30000/scripts/foundry.js:3023
    render https://foundryvtt.piekert.de:30000/scripts/foundry.js:4261
    render https://foundryvtt.piekert.de:30000/scripts/foundry.js:10808
    _onCreateEmbeddedDocuments https://foundryvtt.piekert.de:30000/scripts/foundry.js:10909
    _onCreateEmbeddedDocuments https://foundryvtt.piekert.de:30000/scripts/foundry.js:13777
    _handleCreateEmbeddedDocuments https://foundryvtt.piekert.de:30000/scripts/foundry.js:10068
    _createEmbeddedDocuments https://foundryvtt.piekert.de:30000/scripts/foundry.js:9957
    create https://foundryvtt.piekert.de:30000/common/abstract/backend.mjs:95
    createDocuments https://foundryvtt.piekert.de:30000/common/abstract/document.mjs:338
    createEmbeddedDocuments https://foundryvtt.piekert.de:30000/common/abstract/document.mjs:522
    createEmbeddedDocuments https://foundryvtt.piekert.de:30000/systems/forbidden-lands/forbidden-lands.js:1
    _onDropItemCreate https://foundryvtt.piekert.de:30000/scripts/foundry.js:48284
    _onDropItem https://foundryvtt.piekert.de:30000/scripts/foundry.js:48252
    _onDrop https://foundryvtt.piekert.de:30000/scripts/foundry.js:48199
    _onDrop https://foundryvtt.piekert.de:30000/systems/forbidden-lands/forbidden-lands.js:1
    callback https://foundryvtt.piekert.de:30000/scripts/foundry.js:44455
    _handleDrop https://foundryvtt.piekert.de:30000/scripts/foundry.js:44506
[foundry.js:319:30](https://foundryvtt.piekert.de:30000/scripts/foundry.js)
​`

Is there some error somewhere due to the constant upgrading of foundry, game modules, plugins?

**Comment by aMediocreDad** [comment] 2022-03-11 11:29
Try disabling the `journal-links` module.

**Comment by florianpiekert** [comment] 2022-03-11 11:32
Yes, I disabled that module. No change in behaviour regarding the weight allowance, but no error anymore. So that didnt solve the problem. Any ideas where to dig further?

**Comment by aMediocreDad** [comment] 2022-03-11 12:57
Disable all modules to begin with if you haven't already. This is one of the requirements of the checklist you are presented with when posting a bug report (pasted under for reference):

**Checklist**
Before posting a bug make sure you have disabled all modules and checked if the issue is still present.
- [] Done a clean install of the system.
- [] Disabled all modules.
- [] Checked if the issue is present in a new world instance.
- [] Not a "How To"-question.


I just tested in a clean system with German localization, made a new character and created a Talent that increases encumbrance capacity. If you can reproduce it following the checklist above, then please do come back with reproducible instructions.

**Comment by florianpiekert** [comment] 2022-03-11 13:18
All Modules are disabled. No change in behaviour. Clean install at the moment not possible. Perhaps at a later stage, when we finally get all the german compendiums exported and properly reimported again.

**Comment by aMediocreDad** [comment] 2022-03-11 13:50
And you can reproduce this in a new world instance?

**Comment by aMediocreDad** [comment] 2022-07-03 18:11
Closing this as it has not seen any activity recently. If you are still facing this problem please reopen and provide the steps required to reproduce this.

**Closed by aMediocreDad** 2022-07-03 18:11 UTC
Labels: bug, cannot reproduce
